# Generated by Django 2.1.5 on 2019-05-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('nome_empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
